// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20201015141338_change06")]
    partial class change06
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.AttendanceAnalysis", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("date");

                    b.Property<bool>("early_leave")
                        .HasColumnType("bool");

                    b.Property<TimeSpan>("early_leave_tm")
                        .HasColumnType("time");

                    b.Property<string>("emp_name")
                        .IsRequired()
                        .HasColumnType("char(30)");

                    b.Property<DateTime>("first_tm")
                        .HasColumnType("datetime");

                    b.Property<bool>("half_late")
                        .HasColumnType("bool");

                    b.Property<TimeSpan>("half_late_tm")
                        .HasColumnType("time");

                    b.Property<string>("job_num")
                        .IsRequired()
                        .HasColumnType("char(5)");

                    b.Property<DateTime>("last_tm")
                        .HasColumnType("datetime");

                    b.Property<bool>("late")
                        .HasColumnType("bool");

                    b.Property<bool>("late_or_early_leave")
                        .HasColumnType("bool");

                    b.Property<TimeSpan>("late_tm")
                        .HasColumnType("time");

                    b.Property<bool>("no_attnd")
                        .HasColumnType("bool");

                    b.Property<bool>("only_half_late")
                        .HasColumnType("bool");

                    b.Property<bool>("perfect")
                        .HasColumnType("bool");

                    b.Property<byte>("shift")
                        .HasColumnType("tinyint");

                    b.Property<byte>("times")
                        .HasColumnType("tinyint");

                    b.Property<byte>("week")
                        .HasColumnType("tinyint");

                    b.HasKey("id");

                    b.ToTable("AttendanceAnalysis");
                });

            modelBuilder.Entity("Domain.AttendanceInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("card_id")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<string>("emp_name")
                        .IsRequired()
                        .HasColumnType("char(30)");

                    b.Property<DateTime>("inout_time")
                        .HasColumnType("datetime");

                    b.Property<string>("job_num")
                        .IsRequired()
                        .HasColumnType("char(5)");

                    b.Property<bool>("pass")
                        .HasColumnType("bool");

                    b.Property<byte>("place")
                        .HasColumnType("tinyint");

                    b.Property<int>("seq_num")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("AttendanceInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
